name: Add Label to New PR

on:
  pull_request:
    types:
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: v2 # Optional: specify the version of the action to use

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Explicitly specify Node.js version to use

      - name: Add label
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          NEW_LABEL="ðŸ‘€ë¦¬ë·°í•„ìš”"
          ENCODED_LABEL=$(python -c "import urllib.parse; print(urllib.parse.quote_plus('$NEW_LABEL'))")
          PR_NUMBER=$(jq -r ".number" "$GITHUB_EVENT_PATH")
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"labels\":[\"$ENCODED_LABEL\"]}" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/labels"
